[build-system]
requires = [
    "setuptools >= 61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
markers = [
    "mysql8",
    "mysql5_7: tests specific for mysql 5.7",
]