name: Service_test
on:
  workflow_dispatch:

jobs:
  test_runner:
    name: CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: test_db
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_db
          MYSQL_PASSWORD: test_db
          log_bin_trust_function_creators: 1
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: mysql version
        run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SELECT @@VERSION"